### ISSUE TITLE
Cannot recompile sharefiles

### ISSUE THREAD

**Issue by hrishioa** [eurostat/searoute#21]
I'm not a java developer, so some of these may be (hopefully) simple problems I'm running into.
I'm trying to make sure that ships routed around Somalia and Yemen follow the IRTC rather than the other shipping routes in the GeoJSON. I'm able to edit the marnet files to remove some nodes, but I'm unable to regenerate the shapefiles. I'm missing `mar_ais_gisco.geojson` and `ef.geojson` which don't seem to be included in the repository.

In addition, is it possible for me to package a new jar from the repo? I'm not really familiar with Maven here so any help is appreciated. 

Thanks again for the amazing resource! I've also packaged the code into a Jetty server running inside a Docker container here - https://hub.docker.com/r/hrishioa/gw-sr. Please feel free to use as you see fit if it helps the project!

**Comment by mhadjis** [comment]
Hi hrishioa,
Can you explain how you could modify the marnet files and then create a new file?
Tool (QGIS) or another ?
What steps are needed to achieve this?
Many thanks in advance for your assistance, and I am looking forward to hearing from you.

**Comment by hrishioa** [comment]
Hi - I'm modifying the marnet files (only the geojson) by directly editing them to remove certain edges. I'm having similar trouble as you with the shapefiles, so I'm now trying to see if I can invalidate the edges by detecting them in code, the same way it's being done for Suez and Panama.

**Comment by jgaffuri** [comment]
Dear hrishioa,
_mar_ais_gisco.geojson_ and _ef.geojson w_ files are not included indeed because they were part of an experiment. You can simply remove them from the list.
To produce a new package, simply run _mvn package_ command.
Thanks a lot for the contenarised version ! I will have a look.

**Comment by hrishioa** [comment]
Thanks!

`mvn package` doesn't seem to recompile the shapefiles. How can I get them to be regenerated from the geoJSON files?

I ended up implementing IRTC-detection in software. I've updated the docker container with the new code, which is hosted here: https://github.com/hrishioa/searoute-irtc-docker.

**Comment by mhadjis** [comment]
> Thanks!
> 
> `mvn package` doesn't seem to recompile the shapefiles. How can I get them to be regenerated from the geoJSON files?
> 
> I ended up implementing IRTC-detection in software. I've updated the docker container with the new code, which is hosted here: https://github.com/hrishioa/searoute-irtc-docker.

Dear hrishioa,
Just run this class : **_eu.europa.ec.eurostat.searoute.w.MarnetBuildingMain_** to produce shp filea.
I have another question: how did you produce the points for **IRTC-detection** ? manually or automatic ?
BR
Manu

**Comment by hrishioa** [comment]
Hi Manu,
Thanks! For IRTC detection, I'm simply weighting the edges higher for the non-IRTC nodes, same as being done with Suez and Panama when they need to be switched off.
Hrishi
