### ISSUE TITLE
Help or contribute to this project

### ISSUE THREAD

**Issue by mhadjis** [eurostat/searoute#24]
**Congratulations on your excellent work.**

I would like to help or contribute to this project.

However, I'm a _senior Java Developer_ and I have **no experience with GIS**.
I want to deepen my knowledge.

I downloaded the QGIS tool to open the .shp file to understand how points are organized but I have still not managed to understand the logic.

I would like to know what you did, that is to say to create Points from Coordinate Data 
and put them in a .shp file.

For instance, create a network with a resolution 75 km.

What steps are needed to achieve this?

Many thanks in advance for your assistance, and I am looking forward to hearing from you.
Emmanuel

**Comment by jgaffuri** [comment]
Thanks a lot Emmanuel ! I am currently working on other projects and do not have much time to dedicate to searoute lib. Feel free to fork and propose pushes. To create the lines used to produce the maritime network, you can use QGIS or any other GIS software with digitalisation capability.
The maritime networks (with several resolutions) can then be generated automatically with _MarnetBuilding_ class.

**Comment by mhadjis** [comment]
> Thanks a lot Emmanuel ! I am currently working on other projects and do not have much time to dedicate to searoute lib. Feel free to fork and propose pushes. To create the lines used to produce the maritime network, you can use QGIS or any other GIS software with digitalisation capability.
> The maritime networks (with several resolutions) can then be generated automatically with _MarnetBuilding_ class.

Thank you for the speedy response!
I have another question: Which method did you use to produce the marnet_densified.geojson file from the AIS data files?
Do you have any examples?
