### ISSUE TITLE
Errors when calculating some routes

### ISSUE THREAD

**Issue by dannyfraser** [eurostat/searoute#29]
I'm trying to calculate the distance between a set of routes (~80,000) and some are raising errors. I've tried taking samples of 100 routes at a time and running them through the .jar file to narrow down which were the exceptions. Here's one example from Indonesia to Egypt - I can provide more if necessary but it's a bit of detective work to find them.

I ran this with both Panama and Suez canals unavailable.

| route name | olat | olon | dlat | dlon |
|---|---|---|---|---|
Bontang_Safaga | 0.101287 | 117.470056 | 29.635942 | 32.380686 |

Can you help to identify the reason that this route is failing?

**Comment by dannyfraser** [comment]
A little more detective work has shown that connections to Ain Sokhna and Colon also raise errors. My hunch is that it's because these ports are in proximity to the end points of the Suez and Panama canals respectively.

Coordinates:
| route name | olat | olon | dlat | dlon |
|---|---|---|---|---|
| Arzew_Colon | 35.810036 | -0.259368 | 9.34731 | -79.904864 |
| Arzew_Safaga | 35.810036 | -0.259368 | 29.635942 | 32.380686|

**Comment by jgaffuri** [comment]
I fixed the mistake... it should work for these cases now.
