### ISSUE TITLE
Maven dependency issue

### ISSUE THREAD

**Issue by totlot-dev-badger** [eurostat/searoute#30]
Hello,
Thanks for sharing this great work,
I am trying to make it work on eclipse but I get an error while adding the dependency to the pom.xml file. The mvn clean install worked properly but once I get on eclipse, the build fails.

Here is the error message I get:
`[INFO] Building total 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from : http://central.maven.org/maven2/org/eclipse/emf/org.eclipse.emf.common/maven-metadata.xml
[INFO] Downloading from : https://repo.boundlessgeo.com/main/org/eclipse/emf/org.eclipse.emf.common/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from/to central.maven.org (http://central.maven.org/maven2): central.maven.org
[WARNING] Could not transfer metadata org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from/to boundless (https://repo.boundlessgeo.com/main/): repo.boundlessgeo.com
[INFO] Downloading from : https://repo.boundlessgeo.com/main/org/eclipse/emf/org.eclipse.emf.ecore/maven-metadata.xml
[INFO] Downloading from : http://central.maven.org/maven2/org/eclipse/emf/org.eclipse.emf.ecore/maven-metadata.xml
[WARNING] Could not transfer metadata org.eclipse.emf:org.eclipse.emf.ecore/maven-metadata.xml from/to central.maven.org (http://central.maven.org/maven2): central.maven.org
[WARNING] Could not transfer metadata org.eclipse.emf:org.eclipse.emf.ecore/maven-metadata.xml from/to boundless (https://repo.boundlessgeo.com/main/): repo.boundlessgeo.com
[WARNING] Failure to transfer org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from http://central.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central.maven.org has elapsed or updates are forced. Original error: Could not transfer metadata org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from/to central.maven.org (http://central.maven.org/maven2): central.maven.org
[WARNING] Failure to transfer org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from https://repo.boundlessgeo.com/main/ was cached in the local repository, resolution will not be reattempted until the update interval of boundless has elapsed or updates are forced. Original error: Could not transfer metadata org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from/to boundless (https://repo.boundlessgeo.com/main/): repo.boundlessgeo.com
[WARNING] Failure to transfer org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from http://central.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central.maven.org has elapsed or updates are forced. Original error: Could not transfer metadata org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from/to central.maven.org (http://central.maven.org/maven2): central.maven.org
[WARNING] Failure to transfer org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from https://repo.boundlessgeo.com/main/ was cached in the local repository, resolution will not be reattempted until the update interval of boundless has elapsed or updates are forced. Original error: Could not transfer metadata org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from/to boundless (https://repo.boundlessgeo.com/main/): repo.boundlessgeo.com
[WARNING] Failure to transfer org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from http://central.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central.maven.org has elapsed or updates are forced. Original error: Could not transfer metadata org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from/to central.maven.org (http://central.maven.org/maven2): central.maven.org
[WARNING] Failure to transfer org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from https://repo.boundlessgeo.com/main/ was cached in the local repository, resolution will not be reattempted until the update interval of boundless has elapsed or updates are forced. Original error: Could not transfer metadata org.eclipse.emf:org.eclipse.emf.common/maven-metadata.xml from/to boundless (https://repo.boundlessgeo.com/main/): repo.boundlessgeo.com
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.347 s
[INFO] Finished at: 2020-04-22T00:15:00+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project total: Could not resolve dependencies for project dist:total:jar:0.0.1-SNAPSHOT: Failure to find eu.europa.ec.eurostat:searoute:jar:1.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.`

Thanks a lot if by any chance you can help me with this issue,

**Comment by jgaffuri** [comment]
I fixed a mistake in the OSgeo repository. You can check again now, it should be working.
