### ISSUE TITLE
More information on AIS route enrichment

### ISSUE THREAD

**Issue by tomBoltson** [eurostat/searoute#34]
Searoute as a library works great. But with the exception of Europe mostly, the routes are sparse. I've tried to enrich the data file with a ton of additional AIS routes (based on a year of somewhat cleaned AIS data). It took a while to run MarnetBuilding but in the end I came up with some rather strange route recommendations (e.g Rotterdam to New York had a detour up to Scotland and back). 
How did you come up with your AIS routes? Do I just have to be more careful with my data set or do I need a special preprocessing?

**Comment by jgaffuri** [comment]
Hi,
You can indeed have strange routes when the network simplification level is too high. The network used by default is a schematic one which is indeed not always detailed enough for some other parts of the world outside of Europe... If you can share some more information on the problematic case you described, I could help checking it.
