### ISSUE TITLE
Arctic routes in marine network

### ISSUE THREAD

**Issue by dannyfraser** [eurostat/searoute#39]
Is it possible to add Arctic routes (Northwest Passage & Northern Sea Route) as options to the shipping network?

https://en.wikipedia.org/wiki/Arctic_shipping_routes

**Comment by jgaffuri** [comment]
It is currenlty not possible. You can however use the program with a custom maritime network covering the Artic routes.

**Comment by iskandari** [comment]
@jgaffuri would it be possible to add instructions or a basic example to the readme on how to use searoute with a custom maritime network? This is really a great project - it works right out of the box. Thanks for making it public!

**Comment by jgaffuri** [comment]
This should be in the next release
