### ISSUE TITLE
strange routing anomaly

### ISSUE THREAD

**Issue by Bakr78** [eurostat/searoute#40]
Why there is a strange zigzag routing from port of Klang to yangon - see attachment
![image](https://user-images.githubusercontent.com/56658206/88211600-f9543f80-cc66-11ea-8b4b-b930ecae6921.png)
that issue was in version 1.0 as well as in 2.1

you can reproduce as per this link:

http://127.0.0.1:8080/searoute-war/searoute.html?opos=132.894718,%2042.772166,101.319008,%202.971487&dpos=101.319008,%202.971487,96.353411,%2016.321326&fs=1
 
thanks.

**Comment by jgaffuri** [comment]
This happens because the maritime network dataset you are using is too schematic. Try using the one with 5km resolution maybe?
