### ISSUE TITLE
Excellent project

### ISSUE THREAD

**Issue by giuliohome** [eurostat/searoute#44]
Just to say thank you for sharing.
I remember I came here a year ago and I appreciated it a lot (but maybe it was difficult for me to understand the details).
Now I've really started using the latest release inside a web project (flask py). Very good to see the options to avoid the canals!
Moreover only now I realized that even if the engine is Java it's only a matter of downloading and unzipping the jdk, a real setup is not even needed. I also understand now that there is very little or nothing specific to tomcat. At the moment I am redirecting to geojson.io as per your read me but there is a limitation for the max length of url encoding (when done only via a link). But here (I'm looking at that now) there is even the webapp with the ajax and the code for a leaflet front end (usable with any backend, so again, also without war and tomcat). In conclusion, thank you for the great work, for sharing all the code but also for explaining and clarifying a lot of things!

**Comment by jgaffuri** [comment]
Thanks giuliohome ! It is alsways a pleasure to receive such ackowledgement message :-)
