### ISSUE TITLE
exception at finer resolutions

### ISSUE THREAD

**Issue by giuliohome** [eurostat/searoute#45]
I'm getting 
`Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.locationtech.jts.geom.Geometry.getGeometryType()" because "g" is null`
for all resolutions (50, 20) under 100. For 100 it correctly saves the output.
My command is 

```
C:\FreightProj2020\code\searoute-2.1>jdk-15.0.1\bin\java -jar searoute.jar -i  routes\real_routes_2020-12-19_MR1.csv -res 100 -panama 1 -suez 1 -o routes\real_routes_2020-12-19_MR1.geojson
Build maritime network (resolution: 100km)...
2021-01-14 19:06:22 INFO  ENGINE:-1 - dataFileCache open start
Compute maritime routes (nb: 217)...
Save...

C:\FreightProj2020\code\searoute-2.1>jdk-15.0.1\bin\java -jar searoute.jar -i  routes\real_routes_2020-12-19_MR1.csv -res 20 -panama 1 -suez 1 -o routes\real_routes_2020-12-19_MR1.geojson
Build maritime network (resolution: 20km)...
2021-01-14 19:06:38 INFO  ENGINE:-1 - dataFileCache open start
Compute maritime routes (nb: 217)...
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.locationtech.jts.geom.Geometry.getGeometryType()" because "g" is null
        at eu.europa.ec.eurostat.searoute.GeoDistanceUtil.getLengthGeoKM(GeoDistanceUtil.java:37)
        at eu.europa.ec.eurostat.searoute.SeaRouteJarMain.main(SeaRouteJarMain.java:152)

```
Is it a bug or a wrong usage (but where in the latter case?)

**Comment by jgaffuri** [comment]
Could you find more precisely in your "real_routes_2020-12-19_MR1.csv" file for which route this error occurs?

**Comment by giuliohome** [comment]
You're right, sorry, here it is, I'd appreciate if you could have a look, thank you very much in advance.

[real_routes_2020-12-19_MR1.zip](https://github.com/eurostat/searoute/files/5819472/real_routes_2020-12-19_MR1.zip)

**Comment by giuliohome** [comment]
Found this (for example, after a binary search)

```
route name,olon,olat,dlon,dlat
route46,37.3516,44.3101,53.3833,46.1528
```

**Comment by giuliohome** [comment]
it looks like my coordinates for the caspian pipeline consortium terminal are wrong

**Comment by giuliohome** [comment]
Sorry, this is clearly my fault.
Thank you
