### ISSUE TITLE
Running Sea Route with 5km Detailed gpkg file

### ISSUE THREAD

**Issue by EashanGandhi** [eurostat/searoute#50]
![image](https://user-images.githubusercontent.com/87763241/127029077-282d9ca0-f3db-4131-b9dd-526c98caa160.png)

Hello,

I am having the issue, as shown in the image above with the 5km detailed gpkg file and was wondering if you have encountered this issue before? If so, what is the solution?

Thank you.

**Comment by jgaffuri** [comment]
Hi,
Do you have more information which would allow me reproducing the issue?
Could you extract the input data which causes this issue ?
