### ISSUE TITLE
Using the library to route between 10 min difference GPS points

### ISSUE THREAD

**Issue by gorjan** [eurostat/searoute#57]
Hi, I am investigating using a GPS device which can send its location every 10 minutes, to track my boat.
I would like to display the sailed route on map. Currently I am doing so with dots for each location. 
I would like to connect the dots with a line, but would like to take into account islands and other land features. Basically calculate the shortest route between two GPS points, and do so for every point.

Would this library be efficient for the above use case?

**Comment by jgaffuri** [comment]
Hi,
SeaRoute can currently build shortest maritime routes estimates with schematic geometrical levels of detail (for global scale). It is not suitable for your use case unfortunately. To take into account small size islands and land features, it would require building a more detailed maritime network, whose utilisation could have an impact on the performance (computation speed).
